import re

h = open('output/nailsbynicky/index.html').read()

def rep(a, b, n=1):
    global h
    assert a in h, 'NO: ' + a[:160]
    h = h.replace(a, b, n)

# ---------- EXPERIENCIA ----------
rep('<img src="assets/raw/bk-2.jpg" alt="Clienta con look terminado en el sofa amarillo del estudio Pure Artistry" class="blur-up w-full h-full object-cover" loading="lazy" />',
    '<img src="assets/raw/bk-7.jpg" alt="Neon green and black ghost nail art at Nails By Nicky, Hialeah" class="blur-up w-full h-full object-cover" loading="lazy" />')
rep('<img src="assets/raw/bk-6.jpg" alt="Twists recien terminados en Pure Artistry" class="blur-up w-full h-full object-cover" loading="lazy" />',
    '<img src="assets/raw/bk-8.jpg" alt="Soft pink gel manicure with a glitter accent nail at Nails By Nicky" class="blur-up w-full h-full object-cover" loading="lazy" />')
rep('<span data-es="Una estilista," data-en="One stylist,">One stylist,</span><br /><span class="text-shine" data-es="manos de celebridad" data-en="celebrity hands">celebrity hands</span>',
    '<span data-es="Una técnica," data-en="One nail tech,">One nail tech,</span><br /><span class="text-shine" data-es="manos firmes" data-en="steady hands">steady hands</span>')
rep('data-es="Pure Artistry es el estudio privado de una estilista K-Tip specialist que ha peinado a atletas de la NBA y la MLB. Silk press, locs, trenzas y extensiones, todo en un suite uno-a-uno en el centro de Orlando." data-en="Pure Artistry is the private studio of a K-Tip specialist who has styled NBA and MLB athletes. Silk press, locs, braids and extensions, all in a one-on-one suite in downtown Orlando.">Pure Artistry is the private studio of a K-Tip specialist who has styled NBA and MLB athletes. Silk press, locs, braids and extensions, all in a one-on-one suite in downtown Orlando.</p>',
    'data-es="Nails By Nicky es el suite de una sola técnica, Nicky, en Hialeah. Cada set se forma y pinta a mano, desde una Russian manicure hasta un full set de Apres Gel X, en un ambiente que sus clientas describen como relajado y meticuloso." data-en="Nails By Nicky is the suite of one nail tech, Nicky, in Hialeah. Every set is shaped and painted by hand, from a Russian manicure to a full Apres Gel X set, in an atmosphere her clients call relaxed and meticulous.">Nails By Nicky is the suite of one nail tech, Nicky, in Hialeah. Every set is shaped and painted by hand, from a Russian manicure to a full Apres Gel X set, in an atmosphere her clients call relaxed and meticulous.</p>')
rep('data-es="Sus clientas lo confirman: un silk press que dura dos semanas completas en el calor de Orlando. 5.0 perfecto en 234 reseñas verificadas de Booksy." data-en="Her clients confirm it: silk presses that last a full two weeks in the Orlando heat. A perfect 5.0 across 234 verified Booksy reviews.">Her clients confirm it: silk presses that last a full two weeks in the Orlando heat. A perfect 5.0 across 234 verified Booksy reviews.</p>',
    'data-es="El resultado: 4.9 en 71 reseñas verificadas, y clientas que vuelven cita tras cita por la misma atención al detalle y la paciencia de Nicky." data-en="The result: a 4.9 rating across 71 verified reviews, and clients who come back visit after visit for Nicky\'s attention to detail and patience.">The result: a 4.9 rating across 71 verified reviews, and clients who come back visit after visit for Nicky\'s attention to detail and patience.</p>')
rep('<div class="glass glass-hover rounded-2xl p-4 text-center"><p class="font-display text-xl text-shine"><span data-count="5.0" data-decimals="1">5.0</span></p><p class="text-[11px] text-[color:var(--ink-40)] uppercase tracking-wide mt-1">Booksy</p></div>',
    '<div class="glass glass-hover rounded-2xl p-4 text-center"><p class="font-display text-xl text-shine"><span data-count="4.9" data-decimals="1">4.9</span></p><p class="text-[11px] text-[color:var(--ink-40)] uppercase tracking-wide mt-1">Booksy</p></div>')
rep('<div class="glass glass-hover rounded-2xl p-4 text-center"><p class="font-display text-xl text-shine"><span data-count="234">234</span></p><p class="text-[11px] text-[color:var(--ink-40)] uppercase tracking-wide mt-1" data-es="Reseñas" data-en="Reviews">Reviews</p></div>',
    '<div class="glass glass-hover rounded-2xl p-4 text-center"><p class="font-display text-xl text-shine"><span data-count="71">71</span></p><p class="text-[11px] text-[color:var(--ink-40)] uppercase tracking-wide mt-1" data-es="Reseñas" data-en="Reviews">Reviews</p></div>')
rep('<img src="assets/raw/bk-2.jpg" alt="Pure Artistry, estilista" class="blur-up w-10 h-10 rounded-full object-cover ring-1 ring-[rgba(212,75,98,0.3)]" loading="lazy" />\n            <span class="text-sm font-light">Pure Artistry · <span class="text-[color:var(--ink-40)]" data-es="K-Tip Specialist" data-en="K-Tip Specialist">K-Tip Specialist</span></span>',
    '<img src="assets/raw/bk-2.jpg" alt="Nicky, nail tech at Nails By Nicky" class="blur-up w-10 h-10 rounded-full object-cover ring-1 ring-[rgba(212,75,98,0.3)]" loading="lazy" />\n            <span class="text-sm font-light">Nicky · <span class="text-[color:var(--ink-40)]" data-es="Técnica de uñas" data-en="Nail Artist">Nail Artist</span></span>')

# ---------- METODO ----------
rep('data-es="Eliges tu servicio en Booksy con precio y duración claros: silk press, retwist, braids o extensiones, y confirmas al instante." data-en="Pick your service on Booksy with clear price and duration: silk press, retwist, braids or extensions, and confirm instantly.">Pick your service on Booksy with clear price and duration: silk press, retwist, braids or extensions, and confirm instantly.</p>',
    'data-es="Eliges tu servicio en Booksy con precio y duración claros: Russian manicure, Apres Gel X, dip o nail art, y confirmas al instante." data-en="Pick your service on Booksy with clear price and duration: Russian manicure, Apres Gel X, dip or nail art, and confirm instantly.">Pick your service on Booksy with clear price and duration: Russian manicure, Apres Gel X, dip or nail art, and confirm instantly.</p>')
rep('<h3 class="font-display text-xl mb-3" data-es="Consulta capilar" data-en="Hair consult">Hair consult</h3>',
    '<h3 class="font-display text-xl mb-3" data-es="Consulta de uñas" data-en="Nail consult">Nail consult</h3>')
rep('data-es="Tu tipo de cabello, su salud y el estilo que buscas definen la técnica: proteger tu cabello natural es la prioridad." data-en="Your hair type, its health and the style you want define the technique: protecting your natural hair comes first.">Your hair type, its health and the style you want define the technique: protecting your natural hair comes first.</p>',
    'data-es="Forma, largo y el acabado que buscas, desde Russian manicure hasta Apres Gel X, se deciden juntas antes de empezar." data-en="Shape, length and the finish you want, from Russian manicure to Apres Gel X, get decided together before anything touches your nails.">Shape, length and the finish you want, from Russian manicure to Apres Gel X, get decided together before anything touches your nails.</p>')
rep('<h3 class="font-display text-xl mb-3" data-es="Manos a la obra" data-en="The work">The work</h3>',
    '<h3 class="font-display text-xl mb-3" data-es="La aplicación" data-en="The application">The application</h3>')
rep('data-es="Del silk press de 2 horas a las knotless de 7: cada servicio recibe su tiempo completo, sin citas dobles ni apuros." data-en="From the 2-hour silk press to 7-hour knotless braids: every service gets its full time, no double booking, no rushing.">From the 2-hour silk press to 7-hour knotless braids: every service gets its full time, no double booking, no rushing.</p>',
    'data-es="De un Apres Gel X de 1h 30min a un combo de manicura y pedicura luminary de 3h 30min, cada servicio recibe el tiempo que necesita." data-en="From a 1h 30min Apres Gel X set to a 3h 30min luminary manicure and pedicure combo, every service gets the time it needs.">From a 1h 30min Apres Gel X set to a 3h 30min luminary manicure and pedicure combo, every service gets the time it needs.</p>')
rep('<h3 class="font-display text-xl mb-3" data-es="El toque final" data-en="The finish">The finish</h3>',
    '<h3 class="font-display text-xl mb-3" data-es="El acabado" data-en="The finish">The finish</h3>')
rep('data-es="Sales con el acabado que aguanta semanas y las indicaciones para cuidarlo en casa. Tu próxima cita queda agendada." data-en="You leave with a finish that lasts for weeks and the guidance to keep it that way at home. Next visit booked before you go.">You leave with a finish that lasts for weeks and the guidance to keep it that way at home. Next visit booked before you go.</p>',
    'data-es="Sales con un acabado limpio y duradero, con nail art o cristales si los pediste, y tu próxima cita ya agendada." data-en="You leave with a clean, long-lasting finish, nail art or crystals if you added them, and your next visit already booked.">You leave with a clean, long-lasting finish, nail art or crystals if you added them, and your next visit already booked.</p>')

open('output/nailsbynicky/index.html', 'w').write(h)
print('experiencia + metodo OK')
