import re

h = open('output/iloveawaxingmiami/index.html').read()

def rep(a, b, n=1):
    global h
    assert a in h, 'NO: ' + a[:160]
    h = h.replace(a, b, n)

# ---------- EXPERIENCIA: grid de 2 imagenes -> 1 imagen real (curaduria: pool dominado por
# graficas promocionales con texto; solo 2 fotos reales de alta resolucion sobreviven, bk-1
# (hero) y bk-4 (aqui). Mejor 1 foto real que rellenar con una segunda de baja calidad. ----------
rep('''<div class="grid grid-cols-2 gap-5">
        <div class="frame zoomable aspect-[3/4] img-reveal">
          <img src="assets/raw/hero-1.jpg" alt="El suite de Lash Bloom con su letrero neon rosa" class="blur-up w-full h-full object-cover" loading="lazy" />
        </div>
        <div class="frame zoomable aspect-[3/4] mt-10 img-reveal" style="transition-delay:140ms">
          <img src="assets/raw/about-2.jpg" alt="Rincon del estudio con letrero neon y repisas rosas" class="blur-up w-full h-full object-cover" loading="lazy" />
        </div>
      </div>''',
    '''<div class="frame zoomable aspect-[4/5] img-reveal">
        <img src="assets/raw/bk-4.jpg" alt="Smooth, freshly waxed skin at I Love Waxing Miami" class="blur-up w-full h-full object-cover" loading="lazy" />
      </div>''')

rep('<span data-es="Un suite zen" data-en="A zen suite">A zen suite</span><br /><span class="text-shine" data-es="hecho para relajarte" data-en="made to unwind in">made to unwind in</span>',
    '<span data-es="Una esteticista," data-en="One esthetician,">One esthetician,</span><br /><span class="text-shine" data-es="una sola cita a la vez" data-en="one appointment at a time">one appointment at a time</span>')
rep('data-es="Lash Bloom es el estudio de una sola artista licenciada y certificada: Yesi. Cada set se diseña sobre tu ojo, pestaña por pestaña, en un suite que sus clientas describen como zen y relajante, con luz neon rosa y calma de verdad." data-en="Lash Bloom is the studio of one licensed, certified artist: Yesi. Every set is designed around your eye, lash by lash, in a suite her clients describe as zen and relaxing, pink neon glow included.">Lash Bloom is the studio of one licensed, certified artist: Yesi. Every set is designed around your eye, lash by lash, in a suite her clients describe as zen and relaxing, pink neon glow included.</p>',
    'data-es="I Love Waxing Miami es el suite privado de Gisele Pozo sobre Biscayne Blvd. Cada cita es de cera brasileña, bikini, cejas, rostro o cuerpo, hecha con la misma técnica cuidadosa que sus clientas describen como cálida, como un abrazo." data-en="I Love Waxing Miami is Gisele Pozo\'s private suite on Biscayne Blvd. Every visit, whether Brazilian, bikini, brow, face or body waxing, is done with the same careful technique her clients describe as warm, like a hug.">I Love Waxing Miami is Gisele Pozo\'s private suite on Biscayne Blvd. Every visit, whether Brazilian, bikini, brow, face or body waxing, is done with the same careful technique her clients describe as warm, like a hug.</p>')
rep('data-es="El resultado: 5.0 perfecto en 86 reseñas verificadas, un programa de lealtad para clientas frecuentes, y mujeres que llevan más de cinco años sin dejarse pestañas con nadie más." data-en="The result: a perfect 5.0 across 86 verified reviews, a loyalty program for regulars, and women who have not trusted their lashes to anyone else in over five years.">The result: a perfect 5.0 across 86 verified reviews, a loyalty program for regulars, and women who have not trusted their lashes to anyone else in over five years.</p>',
    'data-es="El resultado: 5.0 perfecto en 111 reseñas verificadas en Booksy, y clientas que viajan desde otras ciudades para no perder su cita con Gisele." data-en="The result: a perfect 5.0 across 111 verified Booksy reviews, and clients who travel from other cities just to keep their appointment with Gisele.">The result: a perfect 5.0 across 111 verified Booksy reviews, and clients who travel from other cities just to keep their appointment with Gisele.</p>')
rep('<div class="glass glass-hover rounded-2xl p-4 text-center"><p class="font-display text-xl text-shine"><span data-count="86">86</span></p><p class="text-[11px] text-[color:var(--ink-40)] uppercase tracking-wide mt-1" data-es="Reseñas" data-en="Reviews">Reviews</p></div>',
    '<div class="glass glass-hover rounded-2xl p-4 text-center"><p class="font-display text-xl text-shine"><span data-count="111">111</span></p><p class="text-[11px] text-[color:var(--ink-40)] uppercase tracking-wide mt-1" data-es="Reseñas" data-en="Reviews">Reviews</p></div>')
rep('<img src="assets/raw/bk-2.jpg" alt="Lash Bloom" class="blur-up w-10 h-10 rounded-full object-cover ring-1 ring-[rgba(160,74,92,0.3)]" loading="lazy" />\n            <span class="text-sm font-light">Yesi · <span class="text-[color:var(--ink-40)]" data-es="Artista licenciada" data-en="Licensed lash artist">Licensed lash artist</span></span>',
    '<img src="assets/raw/bk-14.jpg" alt="Gisele Pozo, esthetician at I Love Waxing Miami" class="blur-up w-10 h-10 rounded-full object-cover ring-1 ring-[rgba(160,74,92,0.3)]" loading="lazy" />\n            <span class="text-sm font-light">Gisele · <span class="text-[color:var(--ink-40)]" data-es="Esteticista" data-en="Esthetician">Esthetician</span></span>')

# ---------- METODO: 4 pasos de depilacion con cera ----------
rep('<span data-es="Tu cita, pestaña" data-en="Your visit, lash">Your visit, lash</span> <span class="text-shine" data-es="por pestaña" data-en="by lash">by lash</span>',
    '<span data-es="Tu cita, paso" data-en="Your visit, step">Your visit, step</span> <span class="text-shine" data-es="a paso" data-en="by step">by step</span>')
rep('<h3 class="font-display text-xl mb-3" data-es="Reserva online" data-en="Book online">Book online</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Eliges tu set o tu relleno en Booksy con precio y duración claros, y confirmas al instante." data-en="Pick your set or fill on Booksy with clear price and duration, and confirm instantly.">Pick your set or fill on Booksy with clear price and duration, and confirm instantly.</p>',
    '<h3 class="font-display text-xl mb-3" data-es="Consulta" data-en="Consult">Consult</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Reservas en Booksy y conversas con Gisele qué área quieres tratar y qué esperar de tu primera cita." data-en="You book on Booksy and talk with Gisele about the area you want treated and what to expect from your first visit.">You book on Booksy and talk with Gisele about the area you want treated and what to expect from your first visit.</p>')
rep('<h3 class="font-display text-xl mb-3" data-es="Mapeo del ojo" data-en="Eye mapping">Eye mapping</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Forma del ojo, pestaña natural y el efecto que buscas: de ahí sale el diseño clásico, híbrido o volumen." data-en="Eye shape, natural lash and the effect you want: that is where the classic, hybrid or volume design comes from.">Eye shape, natural lash and the effect you want: that is where the classic, hybrid or volume design comes from.</p>',
    '<h3 class="font-display text-xl mb-3" data-es="Preparación" data-en="Prep">Prep</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="La piel se limpia y se prepara para que la cera sujete bien y el resultado sea parejo, sin irritación." data-en="Skin is cleansed and prepped so the wax grips properly and the result comes out even, without irritation.">Skin is cleansed and prepped so the wax grips properly and the result comes out even, without irritation.</p>')
rep('<h3 class="font-display text-xl mb-3" data-es="Aplicación zen" data-en="The zen part">The zen part</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Te recuestas, cierras los ojos y Yesi hace lo suyo: hasta 1h 50min de aplicación tranquila, pestaña por pestaña." data-en="You lie back, close your eyes and Yesi does her thing: up to 1h 50min of unhurried, lash-by-lash application.">You lie back, close your eyes and Yesi does her thing: up to 1h 50min of unhurried, lash-by-lash application.</p>',
    '<h3 class="font-display text-xl mb-3" data-es="La cera" data-en="The wax">The wax</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Gisele aplica la cera con técnica rápida y precisa, sección por sección, para que la cita se sienta lo más cómoda posible." data-en="Gisele applies the wax with a quick, precise technique, section by section, to keep the visit as comfortable as possible.">Gisele applies the wax with a quick, precise technique, section by section, to keep the visit as comfortable as possible.</p>')
rep('<h3 class="font-display text-xl mb-3" data-es="Plan de relleno" data-en="Fill plan">Fill plan</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Sales con tu relleno de 2 o 3 semanas agendado y acumulando puntos del programa de lealtad." data-en="You leave with your 2 or 3 week fill booked and loyalty points adding up.">You leave with your 2 or 3 week fill booked and loyalty points adding up.</p>',
    '<h3 class="font-display text-xl mb-3" data-es="Cuidado final" data-en="Aftercare">Aftercare</h3>\n          <p class="text-sm text-[color:var(--ink-60)] font-light leading-relaxed" data-es="Sales con la piel calmada y recomendaciones claras de cuidado, y tu próxima cita ya agendada." data-en="You leave with calmed skin, clear aftercare tips, and your next appointment already on the books.">You leave with calmed skin, clear aftercare tips, and your next appointment already on the books.</p>')

open('output/iloveawaxingmiami/index.html', 'w').write(h)
print('experiencia + metodo OK')
